In [84]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


In [85]:
#how many negative numbers are there?

In [86]:
y =a[a<0]
len(y)


4

In [87]:
#how many positive numbers are there?


In [88]:
f = a[a>0]
len(f)

5

In [89]:
#How many even positive numbers are there?

In [90]:
ans = a[np.where((a > 0) & (a % 2 ==0))]
len(ans)

3

In [91]:
#If you were to add 3 to each data point, how many positive numbers would there be?

In [92]:
zz = a + 3
wow = zz[zz>0]
len(wow)

10

In [93]:
#If you squared each number, what would the new mean and stddev be?

In [94]:
sq = a * a 


In [95]:
sq.mean()


74.0

In [96]:
sq.std()

144.0243035046516

In [97]:
#center the data set

In [98]:
a.mean()


3.0

In [99]:
c = a - 3
c

array([  1,   7,   9,  20,  -5,  -4,  -3,  -3,  -3,  -9,   0, -10])

In [100]:
#Find z-score for each datapoint in array.

In [101]:
z = ((a - 3)/8.06225774829855)
z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [130]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])




In [132]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list


def sum_of_a():
    return a.sum()
sum_of_a()


In [114]:
#Make a variable named min_of_a to hold the minimum of all the numbers in the above list
def min_of_a():
    return a.min()
min_of_a()

1

In [115]:
#Make a variable named max_of_a to hold the max number of all the numbers in the above list
def max_of_a():
    return a.max()
max_of_a()

10

In [133]:
#make a variable named mean_of_a to hold the average of all the numbers in the above list
def mean_of_a():
    return a.mean()
mean_of_a()


5.5

In [135]:
#Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
def product_of_a():
    return np.product(a)
product_of_a()

3628800

In [137]:
#Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
def squares_of_a():
    return np.square(a)
squares_of_a()

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [138]:
#Make a variable named odds_in_a. It should hold only the odd numbers
def odds_in_a():
    return a[a % 2 != 0]
odds_in_a()

array([1, 3, 5, 7, 9])

In [139]:
#Make a variable named evens_in_a. It should hold only the evens.
def evens_in_a():
    return a[a % 2 == 0]
evens_in_a()

array([ 2,  4,  6,  8, 10])

In [173]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])

In [177]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
def sum_b():
    sum_of_b = b.sum()
    return sum_of_b
sum_b()

33

In [178]:
# Exercise 2 - refactor the following to use numpy. 
def min_b():
    b.min()
    return min_of_b
min_b()


3

In [179]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
def max_b():
    b.max()
    return max_of_b
max_b()



8

In [180]:
# Exercise 4 - refactor the following using numpy to find the mean of b
def mean_b():
    b.mean()
    return mean_of_b
mean_b()

5.5

In [181]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
def product_b():
    product_of_b = np.product(b)
    return product_of_b
product_b()

20160

In [182]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
def square_b():
    square_of_b = np.square(b)
    return square_of_b
square_b()

array([[ 9, 16, 25],
       [36, 49, 64]])

In [186]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
def odds_b():
    return b[b % 2 != 0]
  
odds_b()

array([3, 5, 7])

In [187]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
def evens_b():
    return b[b % 2 == 0]
evens_b()

array([4, 6, 8])

In [189]:
# Exercise 9 - print out the shape of the array b.
np.shape(b)

(2, 3)

In [ ]:
# Exercise 10 - transpose the array b.

In [193]:
# # Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
b = np.zeros((1,6))
b

array([[0., 0., 0., 0., 0., 0.]])

In [60]:
# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)


# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)


# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

# Exercise 9 - print out the shape of the array b.

# Exercise 10 - transpose the array b.

# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.

# Exercise 2 - Determine the standard deviation of c.

# Exercise 3 - Determine the variance of c.

# Exercise 4 - Print out the shape of the array c

# Exercise 5 - Transpose c and print out transposed result.

# Exercise 6 - Get the dot product of the array c with c. 

# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

# Exercise 1 - Find the sine of all the numbers in d

# Exercise 2 - Find the cosine of all the numbers in d

# Exercise 3 - Find the tangent of all the numbers in d

# Exercise 4 - Find all the negative numbers in d

# Exercise 5 - Find all the positive numbers in d

# Exercise 6 - Return an array of only the unique numbers in d.

# Exercise 7 - Determine how many unique numbers there are in d.

# Exercise 8 - Print out the shape of d.

# Exercise 9 - Transpose and then print out the shape of d.

# Exercise 10 - Reshape d into an array of 9 x 2
